kind: PersistentVolume
apiVersion: v1
metadata:
  name: gogs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/efs/gogs"
