kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-mvn
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/efs/jenkins-mvn"
